/* What is the frequency of each different Type value? */
-- Replace Line 18 with your query; DO NOT CHANGE ANYTHING ELSE
-- Your query's result MUST NOT RAISE ANY EXCEPTION which means Your query's result MUST MATCH result set generated by Line 22 to Line 23

DECLARE @expectedCount as INT
DECLARE @actualCount as INT

SET @expectedCount = 2
SET @actualCount = 0

SET @actualCount = (
    SELECT COUNT(1)
    FROM
    (
        SELECT Type, Frequency
        FROM
        (
            SELECT TRIM(Type) as Type, COUNT(Type) as Frequency
            FROM stage.Editions se
            GROUP BY TRIM(se.Type)
        ) actual
        INTERSECT
        (
            SELECT 'Kit   Visual material' Type, 5 Frequency
            UNION SELECT 'Print book', 3
        )
    ) result
)

IF @actualCount = @expectedCount
BEGIN
    PRINT CONCAT('@actualCount=', @actualCount, ' matches @expectedCount=', @expectedCount)
END
ELSE
BEGIN      
    RAISERROR (N'@actualCount=%d does not martch @expectedCount=%d', -- Message text.  
            16, -- Severity,  Exception Message
            1, -- State,  
            @actualCount, -- First argument.  
            @expectedCount -- Second argument
        );
END 