/* Find Title values that start with e */
-- Replace Line 18 with your query; DO NOT CHANGE ANYTHING ELSE
-- Your query's result MUST NOT RAISE ANY EXCEPTION which means Your query's result MUST MATCH result set generated by Line 22

DECLARE @expectedCount as INT
DECLARE @actualCount as INT

SET @expectedCount = 0
SET @actualCount = 0

SET @actualCount = (
    SELECT COUNT(1)
    FROM
    (
        SELECT Title
        FROM
        (
            SELECT title 
            FROM stage.Editions se
            WHERE se.title LIKE 'e%'
        ) actual
        INTERSECT
        (
            SELECT 'Harrap''s anglais : me´thode inte´grale' Title
        )
    ) result
)

IF @actualCount = @expectedCount
BEGIN
    PRINT CONCAT('@actualCount=', @actualCount, ' matches @expectedCount=', @expectedCount)
END
ELSE
BEGIN      
    RAISERROR (N'@actualCount=%d does not martch @expectedCount=%d', -- Message text.  
            16, -- Severity,  Exception Message
            1, -- State,  
            @actualCount, -- First argument.  
            @expectedCount -- Second argument
        );
END 