/* Find Title Frequency */
-- Replace Line 18 with your query; DO NOT CHANGE ANYTHING ELSE
-- Your query's result MUST NOT RAISE ANY EXCEPTION which means Your query's result MUST MATCH result set generated by Line 23 to Line 28

DECLARE @expectedCount as INT
DECLARE @actualCount as INT

SET @expectedCount = 6
SET @actualCount = 0

SET @actualCount = (
    SELECT COUNT(1)
    FROM
    (
        SELECT Title, Frequency
        FROM
        (
            SELECT TRIM(Title) as Title, COUNT(Title) as Frequency
            FROM stage.Editions se
            GROUP BY se.title
        ) actual
        INTERSECT
        (
            SELECT 'Activite´s pour le cadre commun [de re´fe´rence pour les langues, CECRL], B2' Title, 1 Frequency
            UNION SELECT 'German', 1
            UNION SELECT 'Harrap''s anglais : me´thode inte´grale', 3
            UNION SELECT 'Harrap''s anglais me´thode inte´grale : pour de´butants et faux de´butants : pour acque´rir le niveau C1', 1
            UNION SELECT 'Je parle, je pratique le franc¸ais : post-alphabe´tisation pour adultes', 1
            UNION SELECT 'Katten', 1
        )
    ) result
)

IF @actualCount = @expectedCount
--IF @actualCount = 0 (looks like this line was not correct)
BEGIN
    PRINT CONCAT('@actualCount=', @actualCount, ' matches @expectedCount=', @expectedCount)
END
ELSE
BEGIN      
    RAISERROR (N'@actualCount=%d does not martch @expectedCount=%d', -- Message text.  
            16, -- Severity,  Exception Message
            1, -- State,  
            @actualCount, -- First argument.  
            @expectedCount -- Second argument
        );
END 