/* Find Language Frequency */
-- Replace Line 18 with your query; DO NOT CHANGE ANYTHING ELSE
-- Your query's result MUST NOT RAISE ANY EXCEPTION which means Your query's result MUST MATCH result set generated by Line 22 to Line 24

DECLARE @expectedCount as INT
DECLARE @actualCount as INT

SET @expectedCount = 3
SET @actualCount = 0

SET @actualCount = (
    SELECT COUNT(1)
    FROM
    (
        SELECT Language, Frequency
        FROM
        (
            SELECT [Language], COUNT([Language]) as Frequency
            FROM stage.Editions se
            GROUP BY se.[Language]
        ) actual
        INTERSECT
        (
            SELECT 'Dutch' Language, 1 Frequency
            UNION SELECT 'English', 2
            UNION SELECT 'French', 5
        )
    ) result
)

IF @actualCount = @expectedCount
BEGIN
    PRINT CONCAT('@actualCount=', @actualCount, ' matches @expectedCount=', @expectedCount)
END
ELSE
BEGIN      
    RAISERROR (N'@actualCount=%d does not martch @expectedCount=%d', -- Message text.  
            16, -- Severity,  Exception Message
            1, -- State,  
            @actualCount, -- First argument.  
            @expectedCount -- Second argument
        );
END 