/* Find the frequency of each Language for Title Harrap''s anglais : méthode intégrale */
-- Replace Line 18 with your query; DO NOT CHANGE ANYTHING ELSE
-- Your query's result MUST NOT RAISE ANY EXCEPTION which means Your query's result MUST MATCH result set generated by Line 22 to Line 23

DECLARE @expectedCount as INT
DECLARE @actualCount as INT

SET @expectedCount = 2
SET @actualCount = 0

SET @actualCount = (
    SELECT COUNT(1)
    FROM
    (
        SELECT Title, [Language], Frequency
        FROM
        (
            SELECT Title, Language, COUNT(Language) as Frequency
            FROM stage.Editions se
            WHERE se.title = 'Harrap''s anglais : méthode intégrale'
            GROUP BY se.Title, se.Language
        ) actual
        INTERSECT
        (
            SELECT 'Harrap''s anglais : me´thode inte´grale' Title, 'English' Language, 1 Frequency
            UNION SELECT 'Harrap''s anglais : me´thode inte´grale', 'French', 2
        )
    ) result
)

IF @actualCount = @expectedCount
BEGIN
    PRINT CONCAT('@actualCount=', @actualCount, ' matches @expectedCount=', @expectedCount)
END
ELSE
BEGIN      
    RAISERROR (N'@actualCount=%d does not martch @expectedCount=%d', -- Message text.  
            16, -- Severity,  Exception Message
            1, -- State,  
            @actualCount, -- First argument.  
            @expectedCount -- Second argument
        );
END 