/* Find distinct Title values that start with h or H */
-- Replace Line 18 with your query; DO NOT CHANGE ANYTHING ELSE
-- Your query's result MUST NOT RAISE ANY EXCEPTION which means Your query's result MUST MATCH result set generated by Line 22 to Line 23

DECLARE @expectedCount as INT
DECLARE @actualCount as INT

SET @expectedCount = 2
SET @actualCount = 0

SET @actualCount = (
    SELECT COUNT(1)
    FROM
    (
        SELECT Title
        FROM
        (
            SELECT DISTINCT title 
            FROM stage.Editions se
            WHERE se.title LIKE 'h%'
        ) actual
        INTERSECT
        (
            SELECT 'Harrap''s anglais me´thode inte´grale : pour de´butants et faux de´butants : pour acque´rir le niveau C1' Title
            UNION SELECT 'Harrap''s anglais : me´thode inte´grale'
        )
    ) result
)

IF @actualCount = @expectedCount 
BEGIN
    PRINT CONCAT('@actualCount=', @actualCount, ' matches @expectedCount=', @expectedCount)
END
ELSE
BEGIN      
    RAISERROR (N'@actualCount=%d does not martch @expectedCount=%d', -- Message text.  
            16, -- Severity,  Exception Message
            1, -- State,  
            @actualCount, -- First argument.  
            @expectedCount -- Second argument
        );
END 