/* Find the Year Frequency (extract DateEdition YYYY part); result set must have distinct YYYY values */
-- Replace Line 18 with your query; DO NOT CHANGE ANYTHING ELSE
-- Your query's result MUST NOT RAISE ANY EXCEPTION which means Your query's result MUST MATCH result set generated by Line 23 to Line 28

DECLARE @expectedCount as INT
DECLARE @actualCount as INT

SET @expectedCount = 7
SET @actualCount = 0

SET @actualCount = (
    SELECT COUNT(1)
    FROM
    (
        SELECT YearPublished, Frequency
        FROM
        (
            SELECT LEFT(DateEdition, 4) as YearPublished, COUNT(DateEdition) as Frequency
            FROM stage.Editions se
            GROUP BY se.DateEdition
        ) actual
        INTERSECT
        (
            SELECT 1987	YearPublished, 1 Frequency
            UNION SELECT 2005, 1
            UNION SELECT 2006, 1
            UNION SELECT 2007, 1
            UNION SELECT 2011, 2
            UNION SELECT 2015, 1
            UNION SELECT 2018, 1
        )
    ) result
)

IF @actualCount = @expectedCount
BEGIN
    PRINT CONCAT('@actualCount=', @actualCount, ' matches @expectedCount=', @expectedCount)
END
ELSE
BEGIN      
    RAISERROR (N'@actualCount=%d does not martch @expectedCount=%d', -- Message text.  
            16, -- Severity,  Exception Message
            1, -- State,  
            @actualCount, -- First argument.  
            @expectedCount -- Second argument
        );
END 