/* Find different Publication values which Publication contains Paris */
-- Replace Line 18 with your query; DO NOT CHANGE ANYTHING ELSE
-- Your query's result MUST NOT RAISE ANY EXCEPTION which means Your query's result MUST MATCH result set generated by Line 22 to Line 25

DECLARE @expectedCount as INT
DECLARE @actualCount as INT

SET @expectedCount = 4
SET @actualCount = 0

SET @actualCount = (
    SELECT COUNT(1)
    FROM
    (
        SELECT Publication
        FROM
        (
            SELECT *
            FROM stage.Editions se
            WHERE se.Publication LIKE '%Paris%'
        ) actual
        INTERSECT
        (
            SELECT '[Paris] : Cle´ international.' Publication
            UNION SELECT 'Paris : Harrap'
            UNION SELECT 'Paris : Larousse'
            UNION SELECT 'Paris : LLarousse'
        )
    ) result
)

IF @actualCount = @expectedCount
BEGIN
    PRINT CONCAT('@actualCount=', @actualCount, ' matches @expectedCount=', @expectedCount)
END
ELSE
BEGIN      
    RAISERROR (N'@actualCount=%d does not martch @expectedCount=%d', -- Message text.  
            16, -- Severity,  Exception Message
            1, -- State,  
            @actualCount, -- First argument.  
            @expectedCount -- Second argument
        );
END 